### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by Sahil-101** [feldroy/django-crash-starter4#1]
## What happened?
- Assertion error on running the command `coverage run -m pytest`
```
>       assert messages_sent == ["Information successfully updated"]
E       AssertionError: assert [] == ['Information...ully updated']
E         Right contains one more item: 'Information successfully updated'
E         Use -v to get the full diff

everycheese/users/tests/test_views.py:70: AssertionError

```
## What should've happened instead?
- All tests should have been passed

## Steps to reproduce
- run command `coverage run -m pytest`

**Comment by ozer550** [comment]
I and @Sahil-101 mixed the ideas of new and previous test_form_valid function.
